const db = `[{
	"id": "1",
	"img": "Dudhsagar_Falls.jpg",
	"title": "Dudhsagar Falls",
	"tag": ["Falls", "Nature"],
	"little_desc": "Dudhsagar Falls is a four-tiered waterfall located on the Mandovi River in the Indian state of Goa. It is 60 km from Panaji by road and is located on the Madgaon-Belagavi rail route about 46 km east of Madgaon and 80 km south of Belgaum",
	"big_desc": "<h5>Dudhsagar Trek</h5><hr> <p>There has been a lot of hype of Dudhsagar trek being closed for the general public. The Dudhsagar railway trek has been officially closed for the general public but the trek to the Dudhsagar falls bottom is still open for all.</p> <br/><p>There are two routes to reach there. One is starting the trek from Kulem and follow the jeep trail until the bottom of the waterfall. The second option is via the railway track which is roughly around 11 km. You can trek up to the Sonaulim station and join back to the Mud route. This route would save 2 km on the Mud road. During the monsoon season, it is mandatory to hire a guide and get a life jacket in order to start the trek otherwise the entry inside the forest is restricted because the area experiences extremely heavy rainfall and the water displacement around the fall are potentially very large, so it is always better to carry a life jacket.</p>"
}, {
	"id": "2",
	"img": "Aguada_Fort.jpg",
	"title": "Aguada Fort",
	"tag": ["Fort", "Culture"],
	"little_desc": "Fort Aguada is a well-preserved seventeenth-century Portuguese fort, along with a lighthouse,standing in Goa, India, on Sinquerim Beach, overlooking the Arabian Sea.",
	"big_desc": "<h5>Origins and history</h5><hr><p>The fort was constructed in 1612 to guard against the Dutch and the Marathas. It was a reference point for the vessels coming from Europe at that time. This old Portuguese fort stands on the beach south of Candolim, at the shore of the Mandovi River. It was initially tasked with defense of shipping and the nearby Bardez sub-district.</p><p>A freshwater spring within the fort provided water supply to the ships that used to stop by. This is how the fort got its name: Aguada, meaning Water. Crews of passing ships would often visit to replenish their freshwater stores. On the fort stands a four-story Portuguese lighthouse, erected in 1864 and the oldest of its kind in Asia. Built in 1612, it was once the grandstand of 79 cannons. It has the capacity of storing 2,376,000 gallons of water, one of the biggest freshwater storages of the time in whole of Asia. This fort is divided in two segments: the upper part acted as fort and watering station, while the lower part served as a safe berth for Portuguese ships. Whereas the upper part has a moat, underground water storage chamber, gunpowder room, lighthouse, and bastions, it also has a secret escape passage to use during time of war and emergency. The lighthouse at the initial stage is used to emit light once in 7 minutes.</p>"
}, {
	"id": "3",
	"img": "Basilica_of_Bom_Jesus.jpg",
	"title": "Basilica of Bom Jesus",
	"tag": ["Church", "Culture"],
	"little_desc": "The Basilica of Bom Jesus is a Roman Catholic basilica located in Goa, India, and is part of the Churches and convents of Goa UNESCO World Heritage Site. The basilica is located in Old Goa, former capital of Portuguese India,and holds the mortal remains of St. Francis Xavier.",
	"big_desc": "<h5>History</h5><hr><p>Construction work on the church began in 1594. The church was consecrated in May 1605 by the archbishop, Dom Fr. Aleixo de Menezes. This world heritage monument has emerged as a landmark in the history of Christianity. It contains the body of St. Francis Xavier, a very close friend of St. Ignatius Loyola with whom he founded the Society of Jesus (the Jesuits). Francis Xavier died on Sancian Island, Chuandao , Taishan while en route to continental China on (December 3, 1552).</p><p>This is one of the oldest churches in Goa and in India. The floor is of marble inlaid with precious stones. Apart from the elaborate gilded altars, the interior of the church is simple. The main altar holds a large statue of St. Ignatius of Loyola, the founder of the Society of Jesus (Jesuits), and one of Francis Xavier's companions whose words drew him to a reformed life. What does it profit a man, Ignatius had asked Francis, if he gains the whole world and loses his soul?</p>"
}, {
	"id": "4",
	"img": "anjuana_beach.jpg",
	"title": "Anjuna Beach",
	"tag": ["Beach", "Culture", "Church"],
	"little_desc": "Anjuna ([ɦɔɳzuɳẽ]) is a village located on the coast of North Goa, India. It is a Census Town,one of the twelve Brahmin comunidades of Bardez. It is mostly a tourist destination.Its church, St. Michael's Church, Anjuna, founded in 1595, is dedicated to S. Miguel, and celebrates the feasts of S. Miguel (29 September) and Nossa Senhora Advogada (second week of January).",
	"big_desc": "<h5>History</h5><hr><p>Like all of Goa, Anjuna was long held by the Portuguese. In 1950, it had a population of 5,688, and in 2011 it had 9,636.</p><br/><p><Historian Teresa Albuquerque, reports that the village's name is derived from the Arabic word 'Hanjuman' (meaning merchant guild). Other say, it comes from an Arabic word for change - as people were arriving at Anjuna from the sea, and were looking to change money.</p><br/><p>It was discovered by the hippies during the 60's, then was a center of backpackers and trance parties lovers, and lately became a popular destination for young big-city Indians.</p><h5>Anjuna Beach</h5><hr><p>Anjuna Beach is a beach in Goa, which is located 18 kilometres away from Panaji and 8 kilometres to the west of Mapusa, North Goa. It is situated in Anjuna village of Bardez taluka in North Goa. The beach is the part of a 30 kilometres extended beach coastline along the west coast of Goa by the Arabian sea.</p><p>Attractions close to Anjuna Beach include Anjuna's flea market and Chapora Fort.</p>"

}, {
	"id": "5",
	"img": "Calangute Beach.jpg",
	"title": "Calangute Beach",
	"tag": ["Beach", "Culture"],
	"little_desc": "Calangute is a town in North Goa, famous for its beach. The beach is the largest in North Goa",
	"big_desc": "<h5>Info</h5><hr><p>The beach is the largest in North Goa and visited by thousands of domestic and international tourists alike. The peak tourist season is during Christmas and New Year, and during the summer in May. During the monsoon season, from June through September, the sea can be rough and swimming is prohibited. The beach offers water sport activities like parasailing and water skiing, among others.</p><h5>Demographics</h5><hr><p>As of the 2011 India census, Calangute had a population of 13,810. Males constituted 54% of the population and females 46%. Calangute had an average literacy rate of 73%, higher than the national average of 59.5%; male literacy was 78% and female literacy 67%. 10% of the population was under 6 years of age.</p>"
}, {
	"id": "6",
	"img": "Chapora_Fort.jpg",
	"title": "Chapora Fort",
	"tag": ["Fort", "Culture"],
	"little_desc": "Chapora Fort, located in Bardez, Goa, rises high above the Chapora River. The site was the location of a fort built by Muslim ruler Adil Shah called Shahpura, whose name the Portuguese altered to Chapora. The fort changed hands several times after Portuguese acquired Bardez.",
	"big_desc": "<h5>History</h5><hr><p>Trying to end the Portuguese rule in Goa, Prince Akbar joined his father’s enemies, the Marathas in 1683 and made this place his base camp. It became the northern outpost of the Old Conquests. After the Portuguese recovered from an encounter with the Marathas, they strengthened their northern defences and provided shelter to the people there.</p><p>Across the Chapora river, the Hindu ruler of Pernem, the Maharaja of Sawantwadi who was an old enemy of the Portuguese held the fort for two years. The Portuguese came in 1717, and carried out extensive repairs of the fort, adding features like bastions and a tunnel that extended to the seashore and banks of the Chapora River for emergencies. The fort fell to Bhonsle in 1739.[1] In 1741, the Portuguese regained the fort when the northern taluka of Pernem was handed over to them. In 1892, they completely abandoned the fort.When Goa's border moved northwards with the acquisition of Pernem as part of the New Conquests, the fort lost its military significance towards the end of the century. It is a pleasant place to wander that offers fantastic views north across the Chapora river to Pernem, south over Vagator and also far out to the Arabian Sea in the West.</p>"
}, {
	"id": "7",
	"img": "Se_Cathedral.jpg",
	"title": "Se Cathedral",
	"tag": ["Church", "Culture"],
	"little_desc": "The Sé Catedral de Santa Catarina, known as Se Cathedral, is the cathedral of the Latin Rite Roman Catholic Archdiocese of Goa and Daman and the seat of the Patriarch of the East Indies. It is located in Old Goa, India.",
	"big_desc": "<h5>History</h5><hr><p>The word Sé is Portuguese for See. The Se Cathedral was built to commemorate the victory of the Portuguese under Afonso de Albuquerque over a Muslim army, leading to the capture of the city of Goa in 1510. Since the day of the victory happened to be on the feast of Saint Catherine, the cathedral was dedicated to her.</p><h5>Architecture</h5><hr><p>The architecture style of the Se Cathedral is Portuguese-Manueline. The exterior is Tuscan, whereas the interior is Corinthian. The church is 250 feet (76 m) in length and 181 feet (55 m) in breadth. The frontispiece stands 115 feet (35 m) high.</p><h5>Inside the cathedral</h5><hr><p>The Se Cathedral's tower houses a large bell known as the Golden Bell on account of its rich tone. It is said to be the largest in Goa, and one of the best in the world. The main altar is dedicated to Catherine of Alexandria, and there are several old paintings on either side of it. On the right there is a Chapel of the Cross of Miracles, where a vision of Christ is said to have appeared in 1619. There are six main panels, on which scenes from the life of Saint Catherine are carved. There is a huge gilded reredos above the main altar.</p>"
}, {
	"id": "8",
	"img": "Salim_Ali_Bird_Sanctuary.jpg",
	"title": "Salim Ali Bird Sanctuary",
	"tag": ["Bird Sanctuary", "Culture", "Nature"],
	"little_desc": "Salim Ali Bird Sanctuary is an estuarine mangrove habitat, which is declared as the bird sanctuary, and located on western tip of the Island of Chorão along the Mandovi River, Goa, in India. The sanctuary is named after Salim Ali, the eminent Indian ornithologist.",
	"big_desc": "<h5>Flora and fauna</h5><hr><p>Several species of birds have been recorded and the common species include the striated heron and western reef heron. Other species that have been recorded include the little bittern, black bittern, red knot, jack snipe and pied avocet (on transient sandbanks). The sanctuary is also host to mudskippers, fiddler crabs and other mangrove habitat specialists. A species of crustacean Teleotanais indianis was described based on specimens obtained in the sanctuary.</p>"
}, {
	"id": "9",
	"img": "colva.jpg",
	"title": "Colva",
	"tag": ["Beach", "Culture", "Nature"],
	"little_desc": "Colvá is a coastal village in Salcete, south Goa, on the west coast of India. Colva Beach stretches for around 2.4 kilometres (1.5 mi), part of a beach consisting of about 25 kilometres (16 mi) of powder white sand, lined along its shore by coconut palms and extending from Bogmalo in the north to Cabo de Rama in the south.",
	"big_desc": "<h5>History</h5><hr><p>Colvá was a vast barren uninhabited land with a scenic Arabian Sea beach that had beach plants such as scaevola sericea until a few Harim (Fisherfolk community) settled there as migrants, primarily in the neighbouring village of Benaulim. The mughals, the people of Adil Shahi dynasty preferred the north and hilly regions of Goa, where they built forts and defences, rather than the coastal belt, and hence had not settled the barren land of Colvá. It was the Portuguese conquest which established the western regions of South Goa as a full-fledged human settlement.</p><h5>Colva Beach</h5><hr><p>Colva beach stretches for around 2.4 km, part of a beach consisting of about 25 km of powder white sand, lined along its shore by coconut palms, and extending as far as Bogmalo Beach to the north and Cabo de rama Beach to the South Goa's coastline.[1] Colva is now a famous tourist destination, enjoyed for its beach. The tourist industry is well developed with many budget hotels, guest houses, beach shacks, food stalls, small restaurants and pubs and bars, although these developments have not extended in any large degree to the nightlife.</p>"
}, {
	"id": "10",
	"img": "Church_and_Convent_of_St_Francis_of_Assisi.jpg",
	"title": "Our Lady of the Immaculate Conception Church",
	"tag": ["Church", "Culture", "Nature"],
	"little_desc": "The Our Lady of the Immaculate Conception Church (Igreja de Nossa Senhora da Imaculada Conceição) is located in Panjim, Goa, India. The Church conducts mass every day in English, Konkani, and Portuguese.",
	"big_desc": "<h5>History</h5><hr><p>A chapel was first built in Panaji in 1541, to serve the religious needs of Portuguese sailors at their first port of call in colonial Portuguese India. At that time the settlement was a small fishing village.[3] It became a Parish in 1600, and in 1609 the small chapel was replaced by the present day large church to minister to the residents and sailors.[4] In the 18th century the stairways, in a symmetrical zigzag form, were added to the church. The second largest church bell in Goa was installed in a bell tower in 1871. It was formerly at the Augustinian Monastery on Holy Hill, and was retrieved after the monastery was damaged.</p><h5>Architecture</h5><hr><p>The exterior facade of the church, rich with Portuguese Baroque style architectural elements is painted a bright white to signify the Immaculate virgin, Mary. The tall belfry centered atop the facade houses the bell from the Augustinian Monastery.[2] The imposing façade is distinctive with its two towers and centrally placed taller belfry. It can be seen from a great distance and is often known as the ‘crown’ of Panjim.</p><p>The interior of the church is not extravagant, but is colourful. The main altar, which has an elegant decor, is dedicated to Mother Mary. There are two other intricately carved, gold plated and decorated altars, one each on either side of the main altar. The one to the left is of Jesus's Crucifixion, and the one to the right is of the Our Lady of the Rosary. These two altars are flanked by marble statues of St Peter and St Paul.</p>"
}]`